---
# Kolla-Ansible site playbook integration for Afterglow services

- name: Gather facts for all hosts
  hosts: all
  serial: "{{ kolla_serial | default('0') }}"
  gather_facts: false
  tasks:
    - name: Gather facts
      ansible.builtin.setup:
        filter: "{{ kolla_ansible_setup_filter }}"
        gather_subset: "{{ kolla_ansible_setup_gather_subset }}"
      when:
        - not ansible_facts
  tags: always

- name: Apply role afterglow
  gather_facts: false
  hosts: afterglow
  serial: "{{ kolla_serial | default('0') }}"
  roles:
    - { role: afterglow, tags: afterglow, when: enable_afterglow | default(false) | bool }

- name: Apply role waygate
  gather_facts: false
  hosts: waygate
  serial: "{{ kolla_serial | default('0') }}"
  roles:
    - { role: waygate, tags: waygate, when: enable_waygate | default(false) | bool }

- name: Apply role drover
  gather_facts: false
  hosts: drover
  serial: "{{ kolla_serial | default('0') }}"
  roles:
    - { role: drover, tags: drover, when: enable_drover | default(false) | bool }

- name: Apply role lumen
  gather_facts: false
  hosts: lumen
  serial: "{{ kolla_serial | default('0') }}"
  roles:
    - { role: lumen, tags: lumen, when: enable_lumen | default(false) | bool }
