---
- name: Destroy | Stop and remove Lumen containers
  become: true
  community.docker.docker_container:
    name: "{{ item.value.container_name }}"
    state: absent
  loop: "{{ lumen_services | dict2items }}"
  when: inventory_hostname in groups['lumen']

- name: Destroy | Remove HAProxy Lumen config
  become: true
  ansible.builtin.file:
    path: "{{ lumen_haproxy_services_d }}/lumen.cfg"
    state: absent
  when: inventory_hostname in groups['haproxy']
  notify: Restart haproxy container
