[project]
name = "afterglow-kolla-operator"
version = "0.1.0"
description = "Afterglow Kolla-Ansible operator environment specification"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kolla-ansible @ git+https://opendev.org/openstack/kolla-ansible@34daacfbf2d5987f543787f57535b2bebe7dee19",
    "drover-kolla @ https://github.com/openstack-afterglow/drover/releases/download/v0.2.19/drover_kolla-0.2.19-py3-none-any.whl#sha256=9d11fdc3a07240a3d613ba878102668b0f9b5cf35b5bd3f3ce6e033426a12392",
    "lumen-kolla @ https://github.com/openstack-afterglow/lumen/releases/download/v0.1.8/lumen_kolla-0.1.8-py3-none-any.whl#sha256=fdef6b8ed0a8bb7f48364ba20cc9bb90471b162287d4d33f9cc13105c340a78b",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
