apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: backend-long-timeout
  namespace: {{ .Release.Namespace }}
spec:
  forwardingTimeouts:
    dialTimeout: 30s
    responseHeaderTimeout: 7200s
    idleConnTimeout: 90s
