apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: afterglow-dev
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: afterglow-dev
      useAnnotations: true
