---
- name: Include precheck tasks
  ansible.builtin.import_tasks: precheck.yml
  tags:
    - precheck
    - always

- name: Include preconditions tasks
  ansible.builtin.import_tasks: preconditions.yml
  when: afterglow_run_preconditions | bool
  tags:
    - preconditions
    - deploy
    - upgrade

- name: Include config tasks
  ansible.builtin.import_tasks: config.yml
  tags:
    - config
    - deploy
    - upgrade
    - reconfigure

- name: Include bootstrap tasks
  ansible.builtin.import_tasks: bootstrap_service.yml
  tags:
    - bootstrap
    - deploy

- name: Include deploy tasks
  ansible.builtin.import_tasks: deploy.yml
  tags:
    - deploy
    - upgrade

- name: Include reconfigure tasks
  ansible.builtin.import_tasks: reconfigure.yml
  tags:
    - reconfigure

- name: Include upgrade tasks
  ansible.builtin.import_tasks: upgrade.yml
  tags:
    - upgrade

- name: Include pull tasks
  ansible.builtin.import_tasks: pull.yml
  tags:
    - pull

- name: Include destroy tasks
  ansible.builtin.import_tasks: destroy.yml
  tags:
    - destroy
