---
- name: Configure loadbalancer for Waygate
  ansible.builtin.import_role:
    name: loadbalancer-config
  vars:
    project_name: waygate
    project_services: "{{ waygate_services }}"
  tags: always
