---
galaxy_info:
  role_name: afterglow
  author: jung-geun
  description: Afterglow OpenStack meta-PaaS deployment role for kolla-ansible
  min_ansible_version: "2.14"

dependencies:
  - role: common
  - role: haproxy-config
