---
- name: Apply role afterglow
  gather_facts: false
  hosts:
    - afterglow
    - '&enable_afterglow_True'
  serial: "{{ kolla_serial | default('0') }}"
  roles:
    - { role: afterglow, tags: afterglow, when: enable_afterglow | bool }
