apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: afterglow-dev
  namespace: argocd
  annotations: {}
spec:
  project: afterglow
  source:
    repoURL: "https://github.com/jung-geun/openstack-afterglow.git"
    targetRevision: dev
    path: deploy/k8s-template/overlays/dev
  destination:
    server: "https://kubernetes.default.svc"
    namespace: afterglow-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
