apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: afterglow-dev
resources:
  - ../../base
  - middleware.yaml
  - ingress.yaml
images:
  - name: ghcr.io/jung-geun/afterglow-api
    newTag: dev
    digest: sha256:734453b1ea913188585e3fe4e5742bc3b458e850cd22f9afc8ead57b0b6d5e4d
  - name: ghcr.io/jung-geun/afterglow
    newTag: dev
    digest: sha256:28e7ea9025877830f321ecf3b9b419001921488507025ea1bff5d3db722754f5
