apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: afterglow-dev
resources:
  - ../../base
  - middleware.yaml
  - ingress.yaml
images:
  - name: ghcr.io/jung-geun/afterglow-api
    newTag: dev
    digest: sha256:64cf3241f9c4cf1ea80b404c491dc12b3a39cc3f1636275bbcb4eec4a9f914fa
  - name: ghcr.io/jung-geun/afterglow
    newTag: dev
    digest: sha256:28e7ea9025877830f321ecf3b9b419001921488507025ea1bff5d3db722754f5
