CREATE DATABASE IF NOT EXISTS waygate CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS drover CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS lumen CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'waygate'@'%' IDENTIFIED BY 'dev';
CREATE USER IF NOT EXISTS 'drover'@'%' IDENTIFIED BY 'dev';
CREATE USER IF NOT EXISTS 'lumen'@'%' IDENTIFIED BY 'dev';

GRANT ALL PRIVILEGES ON waygate.* TO 'waygate'@'%';
GRANT ALL PRIVILEGES ON drover.* TO 'drover'@'%';
GRANT ALL PRIVILEGES ON lumen.* TO 'lumen'@'%';
FLUSH PRIVILEGES;
