{{- if .Values.monitoring.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
spec:
  replicas: {{ .Values.monitoring.prometheus.replicas }}
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: {{ .Values.monitoring.prometheus.image }}
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: prometheus-sd-token
              mountPath: /etc/prometheus/sd-token
              subPath: sd-token
              readOnly: true
          resources:
            {{- toYaml .Values.resources.prometheus | nindent 12 }}
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
            items:
              - key: prometheus.yml
                path: prometheus.yml
        - name: prometheus-sd-token
          secret:
            secretName: prometheus-sd-token
{{- end }}
