{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-sd-token
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  sd-token: {{ .Values.secrets.monitoringSDToken | quote }}
{{- end }}
