---
- name: Restart lumen-api container
  become: true
  community.docker.docker_container:
    name: lumen_api
    state: started
    restart: true
  when: inventory_hostname in groups['lumen']

- name: Restart lumen-worker container
  become: true
  community.docker.docker_container:
    name: lumen_worker
    state: started
    restart: true
  when: inventory_hostname in groups['lumen']

- name: Restart haproxy container
  become: true
  community.docker.docker_container:
    name: haproxy
    state: started
    restart: true
  when: inventory_hostname in groups['haproxy']
