apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: afterglow-dev

resources:
  - ../../base

images:
  - name: ghcr.io/jung-geun/afterglow-api
    newTag: dev
  - name: ghcr.io/jung-geun/afterglow
    newTag: dev
